// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FLohln28UUSlyrO2axQZuFigv7VTZxE',
    appId: '1:138273860867:web:f449f198c3e1ddabb78d36',
    messagingSenderId: '138273860867',
    projectId: 'androidy-shop',
    authDomain: 'androidy-shop.firebaseapp.com',
    storageBucket: 'androidy-shop.appspot.com',
    measurementId: 'G-8235PF1M8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0P25RMLgRUea52aC7RWa3gmSRKdViPpo',
    appId: '1:138273860867:android:0a33aeede6790d3eb78d36',
    messagingSenderId: '138273860867',
    projectId: 'androidy-shop',
    storageBucket: 'androidy-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_pQoBOLNNACJjO1OmSiGBuaZKoyr0Xs',
    appId: '1:138273860867:ios:ce45c9c7a9d21376b78d36',
    messagingSenderId: '138273860867',
    projectId: 'androidy-shop',
    storageBucket: 'androidy-shop.appspot.com',
    iosBundleId: 'com.example.androidyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq_pQoBOLNNACJjO1OmSiGBuaZKoyr0Xs',
    appId: '1:138273860867:ios:ce45c9c7a9d21376b78d36',
    messagingSenderId: '138273860867',
    projectId: 'androidy-shop',
    storageBucket: 'androidy-shop.appspot.com',
    iosBundleId: 'com.example.androidyshop',
  );
}
